// Auto-generated flag components mapping
// This file is generated by scripts/generate-flag-index.ts

export const flagComponentLoaders = {
  ["us"]: () => import("./us"),
  ["tw"]: () => import("./tw"),
  ["us-wi"]: () => import("./us-wi"),
  ["mu"]: () => import("./mu"),
  ["it-57"]: () => import("./it-57"),
  ["bz"]: () => import("./bz"),
  ["bm"]: () => import("./bm"),
  ["ci"]: () => import("./ci"),
  ["ru-ce"]: () => import("./ru-ce"),
  ["ru-ba"]: () => import("./ru-ba"),
  ["bq-sa"]: () => import("./bq-sa"),
  ["au-vic"]: () => import("./au-vic"),
  ["ua-kpr"]: () => import("./ua-kpr"),
  ["gb-ork"]: () => import("./gb-ork"),
  ["ch"]: () => import("./ch"),
  ["bl"]: () => import("./bl"),
  ["aw"]: () => import("./aw"),
  ["it-42"]: () => import("./it-42"),
  ["mt"]: () => import("./mt"),
  ["no"]: () => import("./no"),
  ["us-ar"]: () => import("./us-ar"),
  ["mc"]: () => import("./mc"),
  ["tv"]: () => import("./tv"),
  ["vi"]: () => import("./vi"),
  ["aq-ts"]: () => import("./aq-ts"),
  ["tc"]: () => import("./tc"),
  ["ug"]: () => import("./ug"),
  ["tt"]: () => import("./tt"),
  ["ma"]: () => import("./ma"),
  ["nz"]: () => import("./nz"),
  ["lr"]: () => import("./lr"),
  ["us-co"]: () => import("./us-co"),
  ["mv"]: () => import("./mv"),
  ["us-md"]: () => import("./us-md"),
  ["by"]: () => import("./by"),
  ["au"]: () => import("./au"),
  ["bn"]: () => import("./bn"),
  ["us-ms"]: () => import("./us-ms"),
  ["ge-so"]: () => import("./ge-so"),
  ["bo"]: () => import("./bo"),
  ["at"]: () => import("./at"),
  ["ck"]: () => import("./ck"),
  ["it-55"]: () => import("./it-55"),
  ["mw"]: () => import("./mw"),
  ["nl"]: () => import("./nl"),
  ["ls"]: () => import("./ls"),
  ["fr-20r"]: () => import("./fr-20r"),
  ["it-82"]: () => import("./it-82"),
  ["ye"]: () => import("./ye"),
  ["es-ct"]: () => import("./es-ct"),
  ["vn"]: () => import("./vn"),
  ["tf"]: () => import("./tf"),
  ["es-ml"]: () => import("./es-ml"),
  ["zm"]: () => import("./zm"),
  ["et-af"]: () => import("./et-af"),
  ["nl-fr"]: () => import("./nl-fr"),
  ["ms"]: () => import("./ms"),
  ["md"]: () => import("./md"),
  ["sh-ac"]: () => import("./sh-ac"),
  ["co"]: () => import("./co"),
  ["us-nm"]: () => import("./us-nm"),
  ["cx"]: () => import("./cx"),
  ["it-45"]: () => import("./it-45"),
  ["ag"]: () => import("./ag"),
  ["gb-sct"]: () => import("./gb-sct"),
  ["mq-old"]: () => import("./mq-old"),
  ["au-tsi"]: () => import("./au-tsi"),
  ["in-mn"]: () => import("./in-mn"),
  ["tz-zanzibar"]: () => import("./tz-zanzibar"),
  ["ru-cu"]: () => import("./ru-cu"),
  ["af"]: () => import("./af"),
  ["cy"]: () => import("./cy"),
  ["bj"]: () => import("./bj"),
  ["ru-lpr"]: () => import("./ru-lpr"),
  ["aq"]: () => import("./aq"),
  ["cn"]: () => import("./cn"),
  ["it-78"]: () => import("./it-78"),
  ["me"]: () => import("./me"),
  ["la"]: () => import("./la"),
  ["mr"]: () => import("./mr"),
  ["ni"]: () => import("./ni"),
  ["lv"]: () => import("./lv"),
  ["om"]: () => import("./om"),
  ["us-wy"]: () => import("./us-wy"),
  ["tg"]: () => import("./tg"),
  ["sh-ta"]: () => import("./sh-ta"),
  ["wi"]: () => import("./wi"),
  ["tr"]: () => import("./tr"),
  ["ua"]: () => import("./ua"),
  ["yu"]: () => import("./yu"),
  ["mp"]: () => import("./mp"),
  ["lt"]: () => import("./lt"),
  ["mg"]: () => import("./mg"),
  ["lc"]: () => import("./lc"),
  ["as"]: () => import("./as"),
  ["bh"]: () => import("./bh"),
  ["cl"]: () => import("./cl"),
  ["it-52"]: () => import("./it-52"),
  ["ad"]: () => import("./ad"),
  ["in-tn"]: () => import("./in-tn"),
  ["bq-se"]: () => import("./bq-se"),
  ["in-mz"]: () => import("./in-mz"),
  ["in-or"]: () => import("./in-or"),
  ["cz"]: () => import("./cz"),
  ["ae"]: () => import("./ae"),
  ["cm"]: () => import("./cm"),
  ["bi"]: () => import("./bi"),
  ["ar"]: () => import("./ar"),
  ["lb"]: () => import("./lb"),
  ["mf"]: () => import("./mf"),
  ["lu"]: () => import("./lu"),
  ["mq"]: () => import("./mq"),
  ["au-sa"]: () => import("./au-sa"),
  ["es-ce"]: () => import("./es-ce"),
  ["yt"]: () => import("./yt"),
  ["td"]: () => import("./td"),
  ["sg"]: () => import("./sg"),
  ["pk"]: () => import("./pk"),
  ["je"]: () => import("./je"),
  ["hm"]: () => import("./hm"),
  ["gb"]: () => import("./gb"),
  ["it-34"]: () => import("./it-34"),
  ["gu"]: () => import("./gu"),
  ["gnr"]: () => import("./gnr"),
  ["gb-con"]: () => import("./gb-con"),
  ["do"]: () => import("./do"),
  ["gt"]: () => import("./gt"),
  ["us-hi"]: () => import("./us-hi"),
  ["it-21"]: () => import("./it-21"),
  ["kw"]: () => import("./kw"),
  ["us-sc"]: () => import("./us-sc"),
  ["ru"]: () => import("./ru"),
  ["sd"]: () => import("./sd"),
  ["es-ib"]: () => import("./es-ib"),
  ["rw"]: () => import("./rw"),
  ["ph"]: () => import("./ph"),
  ["ss"]: () => import("./ss"),
  ["hn"]: () => import("./hn"),
  ["it-23"]: () => import("./it-23"),
  ["dz"]: () => import("./dz"),
  ["ga"]: () => import("./ga"),
  ["fr"]: () => import("./fr"),
  ["dm"]: () => import("./dm"),
  ["ru-da"]: () => import("./ru-da"),
  ["in-gj"]: () => import("./in-gj"),
  ["cn-xj"]: () => import("./cn-xj"),
  ["ru-ko"]: () => import("./ru-ko"),
  ["gw"]: () => import("./gw"),
  ["us-in"]: () => import("./us-in"),
  ["eh"]: () => import("./eh"),
  ["it-36"]: () => import("./it-36"),
  ["jp"]: () => import("./jp"),
  ["es-pv"]: () => import("./es-pv"),
  ["et-ga"]: () => import("./et-ga"),
  ["sr"]: () => import("./sr"),
  ["se"]: () => import("./se"),
  ["so-sl"]: () => import("./so-sl"),
  ["pm"]: () => import("./pm"),
  ["sv"]: () => import("./sv"),
  ["re"]: () => import("./re"),
  ["sa"]: () => import("./sa"),
  ["io"]: () => import("./io"),
  ["hk"]: () => import("./hk"),
  ["et-sw"]: () => import("./et-sw"),
  ["kp"]: () => import("./kp"),
  ["gb-nir"]: () => import("./gb-nir"),
  ["us-ga"]: () => import("./us-ga"),
  ["kg"]: () => import("./kg"),
  ["gs"]: () => import("./gs"),
  ["gd"]: () => import("./gd"),
  ["it-32"]: () => import("./it-32"),
  ["es-variant"]: () => import("./es-variant"),
  ["pk-jk"]: () => import("./pk-jk"),
  ["iq-kr"]: () => import("./iq-kr"),
  ["ge"]: () => import("./ge"),
  ["gr"]: () => import("./gr"),
  ["in"]: () => import("./in"),
  ["pl"]: () => import("./pl"),
  ["rs"]: () => import("./rs"),
  ["pn"]: () => import("./pn"),
  ["su"]: () => import("./su"),
  ["sb"]: () => import("./sb"),
  ["py"]: () => import("./py"),
  ["il"]: () => import("./il"),
  ["sh-hl"]: () => import("./sh-hl"),
  ["gp"]: () => import("./gp"),
  ["dk"]: () => import("./dk"),
  ["gg"]: () => import("./gg"),
  ["it-25"]: () => import("./it-25"),
  ["af-emirate"]: () => import("./af-emirate"),
  ["cn-xz"]: () => import("./cn-xz"),
  ["bq-bo"]: () => import("./bq-bo"),
  ["gf"]: () => import("./gf"),
  ["dj"]: () => import("./dj"),
  ["gq"]: () => import("./gq"),
  ["ke"]: () => import("./ke"),
  ["im"]: () => import("./im"),
  ["kr"]: () => import("./kr"),
  ["sc"]: () => import("./sc"),
  ["st"]: () => import("./st"),
  ["sy"]: () => import("./sy"),
  ["sn"]: () => import("./sn"),
  ["kh"]: () => import("./kh"),
  ["et-so"]: () => import("./et-so"),
  ["ca-qc"]: () => import("./ca-qc"),
  ["ec"]: () => import("./ec"),
  ["et"]: () => import("./et"),
  ["fo"]: () => import("./fo"),
  ["sl-sealand"]: () => import("./sl-sealand"),
  ["ge-ab"]: () => import("./ge-ab"),
  ["eu"]: () => import("./eu"),
  ["hr"]: () => import("./hr"),
  ["et-sn"]: () => import("./et-sn"),
  ["ki"]: () => import("./ki"),
  ["jm"]: () => import("./jm"),
  ["us-dc"]: () => import("./us-dc"),
  ["mly"]: () => import("./mly"),
  ["pt"]: () => import("./pt"),
  ["so"]: () => import("./so"),
  ["sx"]: () => import("./sx"),
  ["pa"]: () => import("./pa"),
  ["sz"]: () => import("./sz"),
  ["az-artsakh"]: () => import("./az-artsakh"),
  ["sm"]: () => import("./sm"),
  ["jo"]: () => import("./jo"),
  ["it"]: () => import("./it"),
  ["gh"]: () => import("./gh"),
  ["pt-30"]: () => import("./pt-30"),
  ["pk-sd"]: () => import("./pk-sd"),
  ["ua-bpr"]: () => import("./ua-bpr"),
  ["in-ka"]: () => import("./in-ka"),
  ["fm"]: () => import("./fm"),
  ["gi"]: () => import("./gi"),
  ["de"]: () => import("./de"),
  ["es-ga"]: () => import("./es-ga"),
  ["gb-eng"]: () => import("./gb-eng"),
  ["pw"]: () => import("./pw"),
  ["sl"]: () => import("./sl"),
  ["ps"]: () => import("./ps"),
  ["au-nt"]: () => import("./au-nt"),
  ["us-ri"]: () => import("./us-ri"),
  ["kn"]: () => import("./kn"),
  ["hu"]: () => import("./hu"),
  ["et-si"]: () => import("./et-si"),
  ["us-fl"]: () => import("./us-fl"),
  ["au-aboriginal"]: () => import("./au-aboriginal"),
  ["iq"]: () => import("./iq"),
  ["au-wa"]: () => import("./au-wa"),
  ["md-tn"]: () => import("./md-tn"),
  ["ky"]: () => import("./ky"),
  ["gm"]: () => import("./gm"),
  ["er"]: () => import("./er"),
  ["fi"]: () => import("./fi"),
  ["ee"]: () => import("./ee"),
  ["kng"]: () => import("./kng"),
  ["eaf"]: () => import("./eaf"),
  ["pt-20"]: () => import("./pt-20"),
  ["ewe-eth"]: () => import("./ewe-eth"),
  ["es"]: () => import("./es"),
  ["gl"]: () => import("./gl"),
  ["ht"]: () => import("./ht"),
  ["qa"]: () => import("./qa"),
  ["pe"]: () => import("./pe"),
  ["ch-gr"]: () => import("./ch-gr"),
  ["pr"]: () => import("./pr"),
  ["si"]: () => import("./si"),
  ["ro"]: () => import("./ro"),
  ["fr-bre"]: () => import("./fr-bre"),
  ["sk"]: () => import("./sk"),
  ["pg"]: () => import("./pg"),
  ["ir"]: () => import("./ir"),
  ["km"]: () => import("./km"),
  ["ie"]: () => import("./ie"),
  ["ha"]: () => import("./ha"),
  ["kz"]: () => import("./kz"),
  ["fj"]: () => import("./fj"),
  ["gn"]: () => import("./gn"),
  ["gy"]: () => import("./gy"),
  ["au-tas"]: () => import("./au-tas"),
  ["au-act"]: () => import("./au-act"),
  ["knr"]: () => import("./knr"),
  ["eg"]: () => import("./eg"),
  ["fk"]: () => import("./fk"),
  ["au-nsw"]: () => import("./au-nsw"),
  ["id"]: () => import("./id"),
  ["is"]: () => import("./is"),
  ["et-ha"]: () => import("./et-ha"),
  ["pf"]: () => import("./pf"),
  ["qu"]: () => import("./qu"),
  ["va"]: () => import("./va"),
  ["uz"]: () => import("./uz"),
  ["et-be"]: () => import("./et-be"),
  ["oc"]: () => import("./oc"),
  ["ng"]: () => import("./ng"),
  ["us-az"]: () => import("./us-az"),
  ["ot"]: () => import("./ot"),
  ["mk"]: () => import("./mk"),
  ["np"]: () => import("./np"),
  ["cy-nc"]: () => import("./cy-nc"),
  ["it-62"]: () => import("./it-62"),
  ["bd"]: () => import("./bd"),
  ["cw"]: () => import("./cw"),
  ["bs"]: () => import("./bs"),
  ["us-mn"]: () => import("./us-mn"),
  ["kky"]: () => import("./kky"),
  ["us-mo"]: () => import("./us-mo"),
  ["ai"]: () => import("./ai"),
  ["br"]: () => import("./br"),
  ["cv"]: () => import("./cv"),
  ["be"]: () => import("./be"),
  ["us-nc"]: () => import("./us-nc"),
  ["it-77"]: () => import("./it-77"),
  ["ca"]: () => import("./ca"),
  ["us-al"]: () => import("./us-al"),
  ["it-88"]: () => import("./it-88"),
  ["et-ti"]: () => import("./et-ti"),
  ["nf"]: () => import("./nf"),
  ["ly"]: () => import("./ly"),
  ["yo"]: () => import("./yo"),
  ["xk"]: () => import("./xk"),
  ["us-wa"]: () => import("./us-wa"),
  ["ws"]: () => import("./ws"),
  ["th"]: () => import("./th"),
  ["ec-w"]: () => import("./ec-w"),
  ["uy"]: () => import("./uy"),
  ["wf"]: () => import("./wf"),
  ["vu"]: () => import("./vu"),
  ["tj"]: () => import("./tj"),
  ["za"]: () => import("./za"),
  ["us-tx"]: () => import("./us-tx"),
  ["mh"]: () => import("./mh"),
  ["bg"]: () => import("./bg"),
  ["cc"]: () => import("./cc"),
  ["it-75"]: () => import("./it-75"),
  ["gb-wls"]: () => import("./gb-wls"),
  ["us-or"]: () => import("./us-or"),
  ["mt-ce"]: () => import("./mt-ce"),
  ["cu"]: () => import("./cu"),
  ["bf"]: () => import("./bf"),
  ["nr"]: () => import("./nr"),
  ["mi"]: () => import("./mi"),
  ["ne"]: () => import("./ne"),
  ["us-tn"]: () => import("./us-tn"),
  ["zw"]: () => import("./zw"),
  ["tk"]: () => import("./tk"),
  ["vc"]: () => import("./vc"),
  ["ca-bc"]: () => import("./ca-bc"),
  ["to"]: () => import("./to"),
  ["vg"]: () => import("./vg"),
  ["es-cn"]: () => import("./es-cn"),
  ["us-ak"]: () => import("./us-ak"),
  ["mm"]: () => import("./mm"),
  ["li"]: () => import("./li"),
  ["na"]: () => import("./na"),
  ["mz"]: () => import("./mz"),
  ["an"]: () => import("./an"),
  ["cq"]: () => import("./cq"),
  ["bb"]: () => import("./bb"),
  ["cf"]: () => import("./cf"),
  ["id-jt"]: () => import("./id-jt"),
  ["in-as"]: () => import("./in-as"),
  ["ru-dpr"]: () => import("./ru-dpr"),
  ["id-jb"]: () => import("./id-jb"),
  ["cg"]: () => import("./cg"),
  ["ax"]: () => import("./ax"),
  ["it-65"]: () => import("./it-65"),
  ["ao"]: () => import("./ao"),
  ["bt"]: () => import("./bt"),
  ["us-cb"]: () => import("./us-cb"),
  ["ml"]: () => import("./ml"),
  ["fr-cp"]: () => import("./fr-cp"),
  ["et-or"]: () => import("./et-or"),
  ["tn"]: () => import("./tn"),
  ["smi"]: () => import("./smi"),
  ["tl"]: () => import("./tl"),
  ["xx"]: () => import("./xx"),
  ["es-ar"]: () => import("./es-ar"),
  ["mn"]: () => import("./mn"),
  ["nu"]: () => import("./nu"),
  ["my"]: () => import("./my"),
  ["cr"]: () => import("./cr"),
  ["am"]: () => import("./am"),
  ["it-67"]: () => import("./it-67"),
  ["az"]: () => import("./az"),
  ["ba"]: () => import("./ba"),
  ["in-tg"]: () => import("./in-tg"),
  ["ru-ud"]: () => import("./ru-ud"),
  ["au-qld"]: () => import("./au-qld"),
  ["ru-ta"]: () => import("./ru-ta"),
  ["it-72"]: () => import("./it-72"),
  ["cd"]: () => import("./cd"),
  ["al"]: () => import("./al"),
  ["bw"]: () => import("./bw"),
  ["mx"]: () => import("./mx"),
  ["nc"]: () => import("./nc"),
  ["us-ca"]: () => import("./us-ca"),
  ["cl-ei"]: () => import("./cl-ei"),
  ["mo"]: () => import("./mo"),
  ["us-br"]: () => import("./us-br"),
  ["lk"]: () => import("./lk"),
  ["et-am"]: () => import("./et-am"),
  ["ve"]: () => import("./ve"),
  ["tz"]: () => import("./tz"),
  ["tm"]: () => import("./tm")
};

export type FlagComponentName = keyof typeof flagComponentLoaders;

export type FlagCode =
  | "hn"
  | "dm"
  | "fr"
  | "dz"
  | "ga"
  | "it-23"
  | "ph"
  | "ss"
  | "rw"
  | "es-ib"
  | "sd"
  | "in-gj"
  | "ru-da"
  | "ru-ko"
  | "cn-xj"
  | "et-ga"
  | "se"
  | "sr"
  | "it-36"
  | "us-in"
  | "eh"
  | "gw"
  | "es-pv"
  | "jp"
  | "hm"
  | "je"
  | "gu"
  | "gb"
  | "it-34"
  | "pk"
  | "sg"
  | "gb-con"
  | "gnr"
  | "us-sc"
  | "ru"
  | "it-21"
  | "do"
  | "gt"
  | "us-hi"
  | "kw"
  | "sh-hl"
  | "il"
  | "it-25"
  | "gg"
  | "gp"
  | "dk"
  | "sb"
  | "py"
  | "pn"
  | "su"
  | "cn-xz"
  | "af-emirate"
  | "bq-bo"
  | "st"
  | "sc"
  | "dj"
  | "gq"
  | "gf"
  | "kr"
  | "im"
  | "ke"
  | "us-ga"
  | "kg"
  | "gb-nir"
  | "et-sw"
  | "hk"
  | "kp"
  | "io"
  | "gd"
  | "it-32"
  | "gs"
  | "sa"
  | "re"
  | "pm"
  | "sv"
  | "so-sl"
  | "iq-kr"
  | "pk-jk"
  | "es-variant"
  | "rs"
  | "pl"
  | "gr"
  | "ge"
  | "in"
  | "mv"
  | "lr"
  | "us-co"
  | "ma"
  | "nz"
  | "au"
  | "bn"
  | "us-ms"
  | "us-md"
  | "by"
  | "tt"
  | "ug"
  | "tc"
  | "ge-so"
  | "es-ct"
  | "ye"
  | "it-55"
  | "ck"
  | "bo"
  | "at"
  | "it-82"
  | "fr-20r"
  | "ls"
  | "mw"
  | "nl"
  | "mu"
  | "ci"
  | "bm"
  | "it-57"
  | "bz"
  | "tw"
  | "us"
  | "us-wi"
  | "bq-sa"
  | "ru-ba"
  | "ru-ce"
  | "au-vic"
  | "gb-ork"
  | "ua-kpr"
  | "aq-ts"
  | "vi"
  | "tv"
  | "it-42"
  | "bl"
  | "aw"
  | "ch"
  | "mc"
  | "mt"
  | "no"
  | "us-ar"
  | "lc"
  | "mg"
  | "lt"
  | "mp"
  | "it-52"
  | "ad"
  | "cl"
  | "as"
  | "bh"
  | "ua"
  | "wi"
  | "tr"
  | "sh-ta"
  | "yu"
  | "in-tn"
  | "bq-se"
  | "in-or"
  | "in-mz"
  | "yt"
  | "es-ce"
  | "td"
  | "bi"
  | "ar"
  | "cm"
  | "ae"
  | "cz"
  | "au-sa"
  | "mq"
  | "lu"
  | "mf"
  | "lb"
  | "md"
  | "nl-fr"
  | "ms"
  | "ag"
  | "cx"
  | "it-45"
  | "us-nm"
  | "sh-ac"
  | "co"
  | "es-ml"
  | "tf"
  | "vn"
  | "et-af"
  | "zm"
  | "gb-sct"
  | "mq-old"
  | "ru-cu"
  | "au-tsi"
  | "tz-zanzibar"
  | "in-mn"
  | "us-wy"
  | "tg"
  | "cn"
  | "it-78"
  | "ru-lpr"
  | "bj"
  | "aq"
  | "cy"
  | "af"
  | "lv"
  | "om"
  | "mr"
  | "ni"
  | "la"
  | "me"
  | "mh"
  | "us-or"
  | "gb-wls"
  | "cc"
  | "it-75"
  | "bg"
  | "tj"
  | "vu"
  | "wf"
  | "uy"
  | "us-tx"
  | "za"
  | "mt-ce"
  | "zw"
  | "us-tn"
  | "vc"
  | "ca-bc"
  | "tk"
  | "bf"
  | "cu"
  | "ne"
  | "nr"
  | "mi"
  | "mk"
  | "np"
  | "ot"
  | "ng"
  | "us-az"
  | "oc"
  | "bs"
  | "us-mn"
  | "cw"
  | "it-62"
  | "bd"
  | "cy-nc"
  | "va"
  | "uz"
  | "et-be"
  | "kky"
  | "us-wa"
  | "xk"
  | "yo"
  | "ec-w"
  | "ws"
  | "th"
  | "it-77"
  | "ca"
  | "be"
  | "us-nc"
  | "cv"
  | "us-mo"
  | "ai"
  | "br"
  | "ly"
  | "nf"
  | "it-88"
  | "et-ti"
  | "us-al"
  | "my"
  | "mn"
  | "nu"
  | "it-67"
  | "az"
  | "ba"
  | "am"
  | "cr"
  | "tl"
  | "smi"
  | "es-ar"
  | "xx"
  | "ru-ud"
  | "au-qld"
  | "in-tg"
  | "ru-ta"
  | "et-am"
  | "tm"
  | "tz"
  | "ve"
  | "al"
  | "bw"
  | "it-72"
  | "cd"
  | "lk"
  | "mo"
  | "us-br"
  | "cl-ei"
  | "us-ca"
  | "mx"
  | "nc"
  | "na"
  | "mz"
  | "li"
  | "us-ak"
  | "mm"
  | "cf"
  | "bb"
  | "cq"
  | "an"
  | "vg"
  | "to"
  | "es-cn"
  | "id-jt"
  | "id-jb"
  | "ru-dpr"
  | "in-as"
  | "tn"
  | "et-or"
  | "ao"
  | "bt"
  | "ax"
  | "it-65"
  | "cg"
  | "fr-cp"
  | "ml"
  | "us-cb"
  | "jo"
  | "it"
  | "gh"
  | "sm"
  | "az-artsakh"
  | "pa"
  | "sz"
  | "pt-30"
  | "pk-sd"
  | "ua-bpr"
  | "in-ka"
  | "gb-eng"
  | "es-ga"
  | "pw"
  | "sl"
  | "de"
  | "gi"
  | "fm"
  | "kh"
  | "et-so"
  | "et"
  | "fo"
  | "ca-qc"
  | "ec"
  | "sn"
  | "sy"
  | "sl-sealand"
  | "ge-ab"
  | "mly"
  | "sx"
  | "pt"
  | "so"
  | "eu"
  | "us-dc"
  | "jm"
  | "et-sn"
  | "hr"
  | "ki"
  | "ha"
  | "kz"
  | "ie"
  | "km"
  | "ir"
  | "gy"
  | "gn"
  | "fj"
  | "pg"
  | "sk"
  | "fr-bre"
  | "ro"
  | "au-act"
  | "au-tas"
  | "knr"
  | "qu"
  | "et-ha"
  | "pf"
  | "fk"
  | "eg"
  | "is"
  | "id"
  | "au-nsw"
  | "ky"
  | "md-tn"
  | "au-wa"
  | "us-fl"
  | "au-aboriginal"
  | "iq"
  | "kn"
  | "et-si"
  | "hu"
  | "ee"
  | "er"
  | "fi"
  | "gm"
  | "au-nt"
  | "ps"
  | "us-ri"
  | "kng"
  | "ewe-eth"
  | "pt-20"
  | "eaf"
  | "pr"
  | "si"
  | "ch-gr"
  | "pe"
  | "qa"
  | "gl"
  | "es"
  | "ht";

