import { readdir } from "fs/promises";
import { join, basename, extname } from "path";
import { writeFile } from "fs/promises";

const flagsDir = "./src/components/flags";
const outputFile = "./src/components/flags/index.ts";

// Get all flag component files
const files = await readdir(flagsDir);
const flagFiles = files.filter(
  (file) =>
    file.endsWith(".tsx") &&
    file !== "index.ts" &&
    file !== "Skeleton.tsx" &&
    file !== "Fallback.tsx"
);

// Generate component names mapping
const componentNames: string[] = [];

for (const file of flagFiles) {
  const componentName = basename(file, extname(file));
  componentNames.push(componentName);
}

// Create a mapping object with lazy import functions
const mappingEntries = componentNames.map(
  (name) => `  ${name}: () => import("./${name}")`
);

const content = `// Auto-generated flag components mapping
// This file is generated by scripts/generate-flag-index.ts

export const flagComponentLoaders = {
${mappingEntries.join(",\n")}
};

export type FlagComponentName = keyof typeof flagComponentLoaders;
`;

await writeFile(outputFile, content, "utf-8");
console.log(`✅ Generated flag index with ${flagFiles.length} components`);
