import { readdir } from "fs/promises";
import { basename, extname } from "path";
import { writeFile } from "fs/promises";

const flagsDir = "./src/components/flags";
const svgDir = "./src/svg";
const outputFile = "./src/components/flags/index.ts";

// Get all flag component files
const files: string[] = await readdir(flagsDir);
const flagFiles: string[] = files.filter(
  (file: string) => file.endsWith(".tsx") && file !== "index.ts"
);

// Get all SVG files to extract flag codes
const svgFiles: string[] = await readdir(svgDir);
const flagCodes: string[] = svgFiles
  .filter((file: string) => file.endsWith(".svg"))
  .map((file: string) => basename(file, extname(file)));

// Generate component names mapping
const componentNames: string[] = [];

for (const file of flagFiles) {
  const componentName: string = basename(file, extname(file));
  componentNames.push(componentName);
}

// Create a mapping object with lazy import functions
const mappingEntries: string[] = componentNames.map(
  (name: string) => `  ["${name}"]: () => import("./${name}")`
);

// Create FlagCode union type from SVG file names
const flagCodeTypeEntries: string[] = flagCodes.map(
  (code: string) => `  | "${code}"`
);

const content: string = `// Auto-generated flag components mapping
// This file is generated by scripts/generate-flag-index.ts

export const flagComponentLoaders = {
${mappingEntries.join(",\n")}
};

export type FlagComponentName = keyof typeof flagComponentLoaders;

export type FlagCode =
${flagCodeTypeEntries.join("\n")};

`;

await writeFile(outputFile, content, "utf-8");
console.log(
  `✅ Generated flag index with ${flagFiles.length} components and ${flagCodes.length} flag codes`
);
